### ISSUE TITLE
Unable to trigger invalid response

### ISSUE THREAD

**Issue by designvoid** [hotmeteor/spectator#138]
I have a model `Report`
```
    Report:
      allOf:
        - $ref: '#/components/schemas/BaseModel'
        - type: object
          properties:
            type:
              type: string
              enum:
                - report
```

and the `BaseModel`
```
    BaseModel:
      title: Base Model
      x-stoplight:
        id: 699iassraxl1g
      type: object
      properties:
        type:
          type: string
        id:
          type: string
          format: uuid
        attributes:
          type: object
      required:
        - type
        - id
        - attributes
```

And I am trying to trigger a `ResponseValidationException` by forcing the `type` to be something other than `report` in my api response but the test always passes :(

```
        $this->getJsonApi(route('api.leads.index'))
            ->assertValidRequest()
            ->assertValidResponse(200);
```

Any suggestions?
