### ISSUE TITLE
Cannot validate required response

### ISSUE THREAD

**Issue by fmiqbal** [hotmeteor/spectator#142]
I am trying to validate the exact response on the app vs the spec. There are 2 problem:

1. When property exists on the spec, but not on the actual response
2. When property exists on actual response, but should not be per spec

i can solve no 2 with `additionalProperties: fase` , but no 1 got me nothing when using `required` keywords.

The spec : 
```yaml
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "type": "object",
                                    "required": [
                                        "metadata",
                                        "timestamp"
                                    ],
                                    "properties": {
                                        "id": {
                                            "description": "UUID of the object",
                                            "format": "int64",
                                            "type": "integer",
                                            "example": 12
                                        },
                                        "namespace": {
                                            "description": "Where this actions took, preferably service name. Must be exists before",
                                            "type": "string",
                                            "example": "siat-kepegawaian"
                                        },
                                        "action": {
                                            "description": "What is the action",
                                            "type": "string",
                                            "example": "create_user"
                                        },
                                        "actor": {
                                            "description": "Who took the action, Subject, string, can be id, email, username",
                                            "type": "string",
                                            "example": "iqbal@unpad.ac.id"
                                        },
                                        "timestamp": {
                                            "format": "date-time",
                                            "type": "string"
                                        },
                                        "metadata": {
                                            "type": "object"
                                        }
                                    },
                                    "additionalProperties": false
                                }
                            }
                        }
                    },
```

The controller
```php
    public function show(ActivityLog $log): JsonResponse
    {
        $data = $log->only([
            'id',
            // 'namespace',
            // 'action',
            // 'actor',
            // 'timestamp',
        ]);

        return response()->json($data);
    }
```

The test
```php
    public function test_exists_data_returns_200(): void
    {
        $id = $this->activityLog->id;

        $response = $this->getJson(route('logs.show', $id));

        $response
            ->assertValidRequest()
            ->assertValidResponse(200);

    }
```

Actual test result using phpunit:
![image](https://user-images.githubusercontent.com/8409391/225192040-51b553b3-5aa6-411e-a712-bd697cffe5ae.png)

Example of working validation on Postman : 
![image](https://user-images.githubusercontent.com/8409391/225191943-cad0989a-6ed4-4ab6-883f-2798430574de.png)
