### ISSUE TITLE
Incorrectly nested style tag found - it's not dead yet

### ISSUE THREAD

**Issue by philsturgeon** [hotmeteor/spectator#90]
The "Incorrectly nested style tag found." error reported in #69 should have been solved in #78, but even when using the latest version (1.4.0 which that fix was in) I'm still getting this error.

```
  • Tests\Feature\OrganizationTest > it returns a 404 for invalid record
   ErrorException

  Incorrectly nested style tag found.

  at tests/Feature/OrganizationTest.php:17
     13▕ });
     14▕
     15▕ it('returns a 404 for invalid record', function () {
     16▕     $this->getJson("/v1/orgs/nonsense")
  ➜  17▕         ->assertValidRequest()
     18▕         ->assertValidResponse(404);
     19▕ });
     20▕
     21▕ it('returns a valid record', function () {
```

It's particularly upset about this piece of JSON:

```
{
  "id": "61dba741-6a65-3155-b829-6810f40cef1a",
  "name": "Mr. Carol Lang II",
  "orders": []
}
```

The OpenAPI for this model:

```
title: Organization
type: object
description: Any sort of company or charity that wants to pay for the planting of trees.
required:
  - id
  - name
  - orders
properties:
  id:
    type: string
    format: uuid
    example: 61f423e5-3cac-4e82-a520-b233730637bb
  name:
    type: string
    example: Your Amazing Company
  orders:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 53f7bd7b-2ee2-4be4-a15b-e09c76a150f9
        receivedOn:
          type: string
          format: date-time
          example: '2021-11-22T16:37:15.000Z'
        fulfilledOn:
          type: string
          format: date-time
        isFulfilled:
          type: boolean
          default: false
        orderedTrees:
          type: string
          example: '1000'
        plantedTrees:
          type: string
          example: '700'
        href:
          type: string
          format: url
          example: 'https://api.protect.earth/v1/orders/53f7bd7b-2ee2-4be4-a15b-e09c76a150f9.json'
      required:
        - id
        - receivedOn
        - fulfilledOn
        - isFulfilled
        - orderedTrees
        - plantedTrees
        - href
```

My test will work if I use factories to create a bunch of data for the orders, but I should not have to. An empty array is valid to the contract. 

Any ideas on how to make this more clear? It was pretty tricky to debug that with this message in place.
